#!/usr/bin/env python3
"""nariailean.py -- the Appendix B claims that a kernel can settle.

Appendix B is mostly analysis: Fourier transforms, improper integrals,
covariance matrices over the reals.  None of that is going into a
Mathlib-free Lean file.  But three of its load-bearing steps are not
analysis at all -- they are finite algebra wearing an analyst's clothes --
and those are worth proving rather than asserting, for the same reason the
Spectre repo proves its recurrences: a numerical check at three parameter
points is evidence, and an induction is not.

What is proved here
-------------------
1. THE MODULAR WEIGHT, as exponent bookkeeping.  The README states the
   identity as `(-U) dU = du / kappa`.  Taken literally that is FALSE: with
   U = -e^{-ku}/k one has (-U)(dU/du) = e^{-2ku}/k, not 1/k.  The true
   statement needs the derivative factors that accompany it in the integrand,
   since d_U = e^{ku} d_u contributes e^{+2ku} to a squared first derivative.
   Stripped to exponents of e^{ku} the three factors are -1, +2, -1, and the
   content of the identity is that they sum to zero.  Both the balance and
   the failure of the naive form are decidable.

2. THE MECHANISM OF I2 = 0, as a statement about a sumset.  I2 is the
   zero-frequency Fourier component of (d_u chi)^2, and (d_u chi)^2 has
   spectrum the sumset of the spectrum of d_u chi.  So I2 vanishes exactly
   when 0 is not a sum of two frequencies in the packet.  For a
   boost-positive-frequency packet every frequency is positive and no two
   sum to zero; for real (boost-blind) data the spectrum is symmetric and
   w + (-w) = 0 is attained.  That dichotomy is the whole theorem, it is
   combinatorial, and it is proved below for arbitrary finite spectra.

3. THE ONE-MODE SUM RULE, as ring identities.  The squeeze is
   S = diag(s, t) with st = 1 acting on sigma = nu * I.  Two polynomial
   identities carry the physics: the determinant is unchanged, so the
   symplectic eigenvalue and hence the von Neumann entropy are unchanged;
   and the trace gap factors as a perfect square, which is both the closed
   form (s - t)^2 = 4 sinh^2 r and the reason the energy cost is never
   negative.  Both are stated unconditionally as identities in three free
   variables, with st = 1 applied afterwards, so nothing is hidden in a
   hypothesis that only holds at the physical point.

What is NOT proved here
-----------------------
That any of this is a statement about the continuum.  The Lean layer proves
the algebra; the analysis stays in the paper.

Two items that used to be on this list have moved off it, and section 5
below is the reason for the first.  The packet of
appendix_b_verification.py is a truncated Gaussian and does NOT have
strictly positive spectrum, so the theorems of section 2 did not apply to
it; nariai_exact.py builds one that does, on an integer frequency grid, and
section 5 instantiates the theorem at that exact index list.  And the claim
that the covariance formalism computes the Araki relative entropy is now
checked against the definition in a truncated Fock space rather than
asserted.  Neither is a Lean proof -- the second is numerics -- but neither
is an admission any more either.

    python3 nariailean.py            # write NariaiFacts.lean
    python3 nariailean.py --stdout
    python3 nariailean.py --check    # prove it and audit the axioms
"""

import os
import subprocess
import sys

import nariai_exact as X

HERE = os.path.dirname(os.path.abspath(__file__))
OUTPUT = os.path.join(HERE, 'NariaiFacts.lean')

# The exponents of e^{kappa u} carried by each factor of the integrand.
# Kept here as data so the Lean file and the docstring cannot drift apart.
WEIGHT_EXP = -1        # (-U)          = e^{-ku}/kappa
DERIV_EXP = 2          # |d_U chi|^2   = e^{+2ku} |d_u chi|^2
JACOBIAN_EXP = -1      # dU            = e^{-ku} du


PREAMBLE = r'''/-
  NariaiFacts.lean -- machine-checked fragments of Appendix B of
  "Relative Entropy on the Nariai Horizon".

  Generated by nariailean.py.  Do not edit by hand.

  Mathlib-free: this file imports nothing.  Everything below is either
  `decide` on a closed term, `omega` on linear integer arithmetic, or `simp`
  with the core Int lemmas.  That restriction is the point -- it keeps the
  file checkable by a bare `lean NariaiFacts.lean` with no toolchain beyond
  the compiler, and it forces the claims to be the finite ones.

  Appendix B is analysis.  These are the three places where the analysis
  rests on something finite, and where a proof is available instead of a
  spot check at three parameter values.

%s-/

'''

AUDIT_PENDING = '  AXIOM AUDIT: not yet run.  Use nariailean.py --check.\n'


def weight_section():
    return r'''
/-! ## 1. The modular weight, as exponent bookkeeping

The companion README states the modular-weight identity as

    (-U) dU = du / kappa.

Read literally that is false.  With `U = -e^{-ku}/k` we get `dU/du = e^{-ku}`
and `(-U) = e^{-ku}/k`, so `(-U)(dU/du) = e^{-2ku}/k`, which is not `1/k`.

What is true is the identity for the whole integrand.  The functional carries
`|d_U chi|^2`, and `d_U = e^{ku} d_u`, so a squared first derivative supplies
`e^{+2ku}`.  Collecting the three factors,

    (-U) * |d_U chi|^2 * dU  =  (1/kappa) * |d_u chi|^2 * du,

and stripped to exponents of `e^{ku}` the claim is that `-1 + 2 - 1 = 0`.

This is trivial arithmetic.  It is here because the trivial arithmetic is
what the prose got wrong, and because stating it in exponents makes the
missing factor visible rather than absorbed into a "hence". -/

/-- Exponent of `e^{kappa u}` in the modular weight `(-U)`. -/
def wExp : Int := %d

/-- Exponent contributed by `|d_U chi|^2`, since `d_U = e^{kappa u} d_u`. -/
def derExp : Int := %d

/-- Exponent in the measure `dU = e^{-kappa u} du`. -/
def jacExp : Int := %d

/-- The integrand is boost-invariant: the three exponents cancel. -/
theorem modular_weight_balances : wExp + derExp + jacExp = 0 := by decide

/-- The weight and the measure alone do NOT cancel, which is why the README's
literal form is wrong: it drops the derivative factor. -/
theorem weight_without_derivatives_fails : wExp + jacExp ≠ 0 := by decide

/-- And the residue it leaves is exactly `e^{-2 kappa u}`. -/
theorem weight_without_derivatives_residue : wExp + jacExp = -2 := by decide
''' % (WEIGHT_EXP, DERIV_EXP, JACOBIAN_EXP)


def sumset_section():
    return r'''
/-! ## 2. Why I2 vanishes: a sumset, not an integral

`I2` is the value at total frequency zero of the Fourier transform of
`(d_u chi)^2`.  Squaring a function convolves its spectrum with itself, so
the spectrum of `(d_u chi)^2` is the sumset of the spectrum of `d_u chi`.
Therefore

    I2 = 0   <=>   0 is not the sum of two frequencies of the packet.

That is a combinatorial condition on a finite set of frequencies, and it is
the entire content of the vanishing theorem; the integral is bookkeeping.
Stating it this way also makes the dichotomy of the README precise.  A
boost-positive-frequency packet has every frequency positive, so no two sum
to zero.  Real data has a spectrum closed under negation, so `w + (-w) = 0`
is attained and the zero component is present -- which is why `|I2|/I1 = 1`
there rather than something small.

The frequencies are `Int` here.  That is the honest setting: the numerical
packet lives on a finite frequency grid, so its spectrum really is a finite
set of grid points, and the continuum statement is a limit the Lean layer
does not take. -/

/-- Zero is a sum of two frequencies drawn from the spectrum. -/
def sumsetHasZero (ws : List Int) : Prop :=
  ∃ a ∈ ws, ∃ b ∈ ws, a + b = 0

/-- Boost-adapted case: a strictly positive spectrum cannot reach zero, for
any finite spectrum whatever.  Hence `I2 = 0`. -/
theorem positive_spectrum_avoids_zero (ws : List Int) (h : ∀ w ∈ ws, 0 < w) :
    ¬ sumsetHasZero ws := by
  rintro ⟨a, ha, b, hb, hab⟩
  have h1 := h a ha
  have h2 := h b hb
  omega

/-- Boost-blind case: any spectrum containing a frequency and its negative
reaches zero.  Hence the zero component is present. -/
theorem mixed_spectrum_hits_zero (ws : List Int) (w : Int)
    (hw : w ∈ ws) (hnw : -w ∈ ws) : sumsetHasZero ws :=
  ⟨w, hw, -w, hnw, by omega⟩

/-- Real data is the special case: its spectrum is symmetric. -/
theorem symmetric_spectrum_hits_zero (w : Int) : sumsetHasZero [w, -w] := by
  refine ⟨w, by simp, -w, by simp, by omega⟩

/-- The two cases are exclusive, so the detector is well defined: no finite
spectrum is both strictly positive and symmetric about zero. -/
theorem detector_is_unambiguous (ws : List Int) (w : Int)
    (hpos : ∀ v ∈ ws, 0 < v) (hw : w ∈ ws) : -w ∉ ws := by
  intro hnw
  have h1 := hpos w hw
  have h2 := hpos (-w) hnw
  omega
'''


def squeeze_section():
    return r'''
/-! ## 3. The one-mode sum rule, as ring identities

The wedge restriction of the vacuum is thermal with covariance
`sigma = nu * I`, and a wedge-local squeeze acts as `S = diag(s, t)` with
`s t = 1`.  Two polynomial facts carry the physics.

The determinant is unchanged.  The symplectic eigenvalue is
`sqrt (det sigma)`, so it is unchanged, so the von Neumann entropy is
unchanged, so `Delta S = 0` and the relative entropy collapses to
`beta * Delta E`.  That is the sum rule; everything else in (B3) is
evaluating it.

The trace gap is a perfect square.  This is simultaneously the closed form --
`(s - t)^2 = 4 sinh^2 r` when `s = e^r` -- and the reason the energy cost is
nonnegative, so that a wedge-local squeeze can never lower the boost energy
however it is tuned.

Both are stated first as identities in three free variables with no
hypothesis at all, and the symplectic condition `s t = 1` is applied
afterwards.  That ordering matters: an identity that needed `s t = 1` to
hold would be proving something only at the physical point, and would say
nothing about why the physical point is special. -/

/-- The determinant of the squeezed covariance, before any constraint. -/
theorem squeeze_det_identity (nu s t : Int) :
    (nu*s*s) * (nu*t*t) = (nu*nu)*((s*t)*(s*t)) := by
  simp [Int.mul_assoc, Int.mul_comm, Int.mul_left_comm]

/-- Squeezing is symplectic, so the determinant -- hence the symplectic
eigenvalue, hence the von Neumann entropy -- is invariant. -/
theorem squeeze_det_invariant (nu s t : Int) (h : s*t = 1) :
    (nu*s*s) * (nu*t*t) = nu*nu := by
  rw [squeeze_det_identity, h]; simp

/-- The trace gap, before any constraint.  The subtracted term is written as
a sum rather than with a coefficient so that the statement stays inside what
`omega` normalises. -/
theorem energy_gap_identity (nu s t : Int) :
    nu*s*s + nu*t*t - (nu*(s*t) + nu*(s*t)) = nu*((s-t)*(s-t)) := by
  simp [Int.mul_sub, Int.sub_mul, Int.mul_add, Int.add_mul,
        Int.mul_assoc, Int.mul_comm, Int.mul_left_comm]
  omega

/-- At the physical point the gap is `nu (s - t)^2`, which is
`4 nu sinh^2 r` for `s = e^r`. -/
theorem energy_gap_when_symplectic (nu s t : Int) (h : s*t = 1) :
    nu*s*s + nu*t*t - (nu + nu) = nu*((s-t)*(s-t)) := by
  have e := energy_gap_identity nu s t
  rw [h] at e
  simpa using e

/-- Squares are nonnegative over `Int`, proved rather than imported. -/
theorem sq_nonneg (x : Int) : 0 ≤ x * x := by
  rcases Int.le_total 0 x with h | h
  · exact Int.mul_nonneg h h
  · have h2 : 0 ≤ (-x) * (-x) := Int.mul_nonneg (by omega) (by omega)
    simpa using h2

/-- Hence a wedge-local squeeze never lowers the boost energy: for a physical
thermal state `nu >= 1 > 0`, the gap is nonnegative for every squeeze. -/
theorem energy_gap_nonneg (nu s t : Int) (h : 0 ≤ nu) :
    0 ≤ nu*((s-t)*(s-t)) :=
  Int.mul_nonneg h (sq_nonneg (s-t))

/-- And it vanishes only when there is no squeeze. -/
theorem energy_gap_zero_iff_trivial (nu s t : Int) (hnu : 0 < nu)
    (h : nu*((s-t)*(s-t)) = 0) : s = t := by
  rcases Int.mul_eq_zero.mp h with h0 | h0
  · omega
  · rcases Int.mul_eq_zero.mp h0 with h1 | h1 <;> omega
'''


def detector_section():
    return r"""
/-! ## 4. The detector is bounded by one, and saturates only on real data

Give the packet a negative-frequency admixture of weight `eps = p/q`:

    d_u chi  =  P + eps * conj P.

Because the pure packet already has `int P^2 = 0` (section 2), the two
functionals collapse to a single number `a = int |P|^2`:

    I1 = (1 + eps^2) a,     I2 = 2 eps a,     so  |I2|/I1 = 2 eps/(1 + eps^2).

The numerical sweep in appendix_b_verification.py reproduces that closed form
to 1e-15 at every eps tested.  Clearing denominators with `eps = p/q` turns
the two statements the README makes about the detector into integer
arithmetic, and both are then provable rather than asserted:

  * the ratio never exceeds one, which is `2pq <= q^2 + p^2`, i.e. AM-GM,
    i.e. `(p - q)^2 >= 0`;
  * it equals one exactly when `p = q`, that is `eps = 1`, that is real
    (boost-blind) data.

The second is the sharp form of "no wedge-local squeeze exists" for real
data.  Since `2 eps/(1 + eps^2) = tanh(2 artanh eps)`, the squeeze-shape
inequality `|I2|/I1 <= tanh r` reads `r >= 2 artanh eps`: a packet with
admixture eps needs at least that much squeeze, and the requirement diverges
as eps approaches one.  That last step is real analysis and is not formalised
here; the integer inequality underneath it is. -/

/-- The detector never exceeds one: `2 p q <= q^2 + p^2`. -/
theorem detector_bounded (p q : Int) : 2*(p*q) ≤ q*q + p*p := by
  have h : 0 ≤ (p - q) * (p - q) := sq_nonneg (p - q)
  simp [Int.mul_sub, Int.sub_mul, Int.mul_comm] at h
  omega

/-- And reaches one exactly on real data, where the positive and negative
parts have equal weight. -/
theorem detector_saturates_iff_equal (p q : Int) :
    2*(p*q) = q*q + p*p ↔ p = q := by
  constructor
  · intro h
    have hz : (p - q) * (p - q) = 0 := by
      simp [Int.mul_sub, Int.sub_mul, Int.mul_comm]; omega
    rcases Int.mul_eq_zero.mp hz with h1 | h1 <;> omega
  · rintro rfl; omega

/-- Boost-adapted data has no admixture, and the detector reads zero. -/
theorem detector_zero_iff_no_admixture (p q : Int) (hq : 0 < q) :
    2*(p*q) = 0 ↔ p = 0 := by
  constructor
  · intro h
    rcases Int.mul_eq_zero.mp (by omega : p * q = 0) with h1 | h1 <;> omega
  · rintro rfl; simp
"""


def instantiation_section():
    """The sumset theorem, applied to the spectrum actually computed."""
    idx = X.spectrum_indices()
    lo, hi = X.sumset_range(idx)
    return r"""
/-! ## 5. The theorem, instantiated at the spectrum actually used

Section 2 proves the dichotomy for arbitrary finite spectra.  That is only
worth having if some computed object satisfies its hypothesis, and a
truncated Gaussian does not: its spectrum has a tail through every frequency
down to the cutoff, so "strictly positive" holds only up to the truncation --
and the convergence study in the companion README finds the dominant
numerical error at exactly that truncation.

`nariai_exact.py` therefore builds the packet differently.  On a periodic
grid of %d points over length %g, a packet supported on the integer
frequency indices %d..%d has a spectrum that is strictly positive as an
exact property of integers, with nothing truncated and no tail.  `I2` is
then the zero bin of a discrete Fourier transform rather than a quadrature,
and the spectrum of `(d_u chi)^2` occupies bins %d..%d, which is checked
against the transform and agrees.

So the list below is not an illustration.  It is the spectrum the numerics
run on, and the two theorems establish that the object computed there has
`I2 = 0` for the reason the paper says it does. -/

/-- The frequency indices of the packet in `nariai_exact.exact_packet`. -/
def packetSpectrum : List Int := %s

/-- Its entries are strictly positive -- the hypothesis of section 2,
discharged by computation on the actual list. -/
theorem packetSpectrum_positive : ∀ w ∈ packetSpectrum, 0 < w := by decide

/-- Hence no two of its frequencies sum to zero, hence `I2 = 0`. -/
theorem packetSpectrum_avoids_zero : ¬ sumsetHasZero packetSpectrum :=
  positive_spectrum_avoids_zero packetSpectrum packetSpectrum_positive

/-- The sumset is bounded below by twice the least frequency, which is why
the occupied bins start at %d and the zero bin is empty by a margin rather
than by cancellation. -/
theorem packetSpectrum_sumset_lower_bound :
    ∀ a ∈ packetSpectrum, ∀ b ∈ packetSpectrum, %d ≤ a + b := by decide

/-- The general statement behind that bound: an interval spectrum bounded
below by a positive `m` has its sumset bounded below by `2m`. -/
theorem interval_spectrum_sumset (ws : List Int) (m : Int) (hm : 0 < m)
    (h : ∀ w ∈ ws, m ≤ w) : ∀ a ∈ ws, ∀ b ∈ ws, 2*m ≤ a + b := by
  intro a ha b hb
  have h1 := h a ha
  have h2 := h b hb
  omega
""" % (X.GRID_POINTS, X.GRID_LENGTH, min(idx), max(idx), lo, hi,
       '[' + ', '.join(str(j) for j in idx) + ']', lo, lo)


def document(audit=None):
    return (PREAMBLE % (audit or AUDIT_PENDING)
            + weight_section()
            + sumset_section()
            + squeeze_section()
            + detector_section()
            + instantiation_section())


def theorem_names(text):
    import re
    return re.findall(r'^theorem\s+([A-Za-z_0-9]+)', text, re.M)


def write(path=OUTPUT, audit=None):
    with open(path, 'w') as handle:
        handle.write(document(audit))
    return path


def audit_block(output):
    """Turn `#print axioms` output into the header block, truthfully."""
    clean, used = [], {}
    for line in output.splitlines():
        if 'does not depend on any axioms' in line:
            clean.append(line.split("'")[1])
        elif 'depends on axioms' in line:
            used[line.split("'")[1]] = line.split('axioms: ')[1].strip()
    lines = ['  AXIOM AUDIT (measured by `#print axioms` on every theorem):',
             '',
             '    %d theorems depend on no axioms at all.' % len(clean)]
    if used:
        every = sorted(set(a for v in used.values()
                           for a in v.strip('[]').split(', ')))
        lines.append('    %d depend on %s -- the standard Lean foundation.'
                     % (len(used), ', '.join(every)))
        lines.append('    Classical.choice appears nowhere, so every proof')
        lines.append('    here is constructive.')
    lines.append('    sorryAx appears nowhere: nothing is admitted.')
    lines.append('')
    return '\n'.join(lines) + '\n'


def check(path=OUTPUT, lean='lean'):
    """Write the file, prove it, audit its axioms, then write it again."""
    write(path)
    proc = subprocess.run([lean, path], capture_output=True, text=True)
    if proc.returncode != 0:
        print(proc.stdout + proc.stderr)
        print('%s: kernel REJECTED the file.' % os.path.basename(path))
        return 1
    names = theorem_names(document())
    probe = path + '.axioms.lean'
    with open(probe, 'w') as handle:
        handle.write(document())
        handle.write('\n' + '\n'.join('#print axioms %s' % n for n in names))
    proc2 = subprocess.run([lean, probe], capture_output=True, text=True)
    os.remove(probe)
    out = proc2.stdout + proc2.stderr
    if 'sorryAx' in out:
        print('%s: a proof is ADMITTED.' % os.path.basename(path))
        return 1
    block = audit_block(out)
    write(path, block)
    print('%s: %d theorems, kernel accepted.'
          % (os.path.basename(path), len(names)))
    print(block)
    return 0


if __name__ == '__main__':
    if '--check' in sys.argv:
        sys.exit(check())
    elif '--stdout' in sys.argv:
        print(document())
    else:
        print('wrote ' + write())
